# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [49]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [56]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [57]:
data = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data', sep="\s+")

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-3378479630.py:1: SyntaxWarning: invalid escape sequence '\s'
  data = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data', sep="\s+")

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [58]:
data['Yr'] = data['Yr'].apply(lambda x: x+1900)

In [59]:
data = data.rename(columns={'Yr': 'year', 'Mo': 'month', 'Dy': 'day'})
data['Date'] = pd.to_datetime(data[['year', 'month', 'day']])

In [60]:

col = data.pop('Date')
data.insert(0, 'Date', col)
data.drop(columns = ['year', 'month', 'day'], inplace = True)

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [61]:

data.set_index('Date', drop = True, inplace = True)
data.index.dtype

dtype('<M8[ns]')

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [65]:
data.isna().sum().sum()

np.int64(31)

### Step 7. Compute how many non-missing values there are in total.

In [66]:
(-data.isna()).sum().sum()

np.int64(78857)

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [69]:
data.mean().mean()

np.float64(10.227982360836938)

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days

#### A different set of numbers for each location.

In [71]:
loc_stats = data.aggregate(['min', 'max', 'mean', 'std'])

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [74]:
data.transpose().aggregate(['min', 'max', 'mean'])

Date,1961-01-01,1961-01-02,1961-01-03,1961-01-04,1961-01-05,1961-01-06,1961-01-07,1961-01-08,1961-01-09,1961-01-10,...,1978-12-22,1978-12-23,1978-12-24,1978-12-25,1978-12-26,1978-12-27,1978-12-28,1978-12-29,1978-12-30,1978-12-31
min,9.290000,6.500000,6.170000,1.790000,6.17,4.42,4.960,5.9100,4.7500,6.5400,...,2.460000,9.500000,4.790000,0.750000,1.960000,8.080000,5.00,8.71,9.1300,9.5900
max,18.500000,17.540000,18.500000,11.750000,13.33,13.21,14.290,16.6200,15.3700,19.5000,...,13.080000,22.210000,31.710000,13.960000,13.830000,40.080000,41.46,29.58,28.7900,27.2900
mean,13.018182,11.336364,11.641818,6.619167,10.63,8.24,10.385,10.4875,9.8975,10.4775,...,7.000833,15.613333,10.823333,5.729167,6.523333,16.708333,15.15,14.89,15.3675,15.4025

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [75]:
montly_means = data.groupby(data.index.month).mean()

### Step 12. Downsample the record to a yearly frequency for each location.

In [77]:
yearly_means = data.groupby(data.index.year).mean()
yearly_means

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1961,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [78]:
month_year_means = data.groupby(data.index.to_period('M')).mean()

### Step 14. Downsample the record to a weekly frequency for each location.

In [79]:
month_year_means

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1961-01,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [81]:
week_means = data.groupby(data.index.to_period('W')).agg(['min', 'max', 'mean'])

In [82]:
week_means

                         RPT                      VAL                    \
                         min    max       mean    min    max       mean
Date
1960-12-26/1961-01-01  15.04  15.04  15.040000  14.96  14.96  14.960000
1961-01-02/1961-01-08  10.58  18.50  13.541429   6.63  16.88  11.486667
1961-01-09/1961-01-15   9.04  19.75  12.468571   3.54  12.08   8.967143
1961-01-16/1961-01-22   4.92  19.83  13.204286   3.42  14.37   9.862857
1961-01-23/1961-01-29  13.62  25.04  19.880000   9.96  23.91  16.141429
...                      ...    ...        ...    ...    ...        ...
1978-11-27/1978-12-03   9.08  21.29  14.934286   4.54  21.34  11.232857
1978-12-04/1978-12-10   9.92  29.33  20.740000  12.54  24.79  19.190000
1978-12-11/1978-12-17   9.87  23.13  16.758571   3.21  24.04  14.692857
1978-12-18/1978-12-24   6.21  16.62  11.155714   3.63  13.29   8.008571
1978-12-25/1978-12-31   7.21  20.33  14.951429   5.46  17.41  11.801429

                         ROS                     KIL  ...        MUL    CLO  \
                         min    max       mean   min  ...       mean    min
Date                                                  ...
1960-12-26/1961-01-01  13.17  13.17  13.170000  9.29  ...  10.830000  12.58
1961-01-02/1961-01-08   7.62  12.33  10.487143  4.58  ...   8.434286   5.88
1961-01-09/1961-01-15   7.08  19.50  11.958571  0.67  ...   5.712857   2.67
1961-01-16/1961-01-22   7.29  20.79  12.982857  1.04  ...   7.145714   2.71
1961-01-23/1961-01-29  12.67  25.84  18.225714  6.04  ...  14.480000  11.04
...                      ...    ...        ...   ...  ...        ...    ...
1978-11-27/1978-12-03   8.21  24.04  13.941429  0.96  ...   9.011429   3.29
1978-12-04/1978-12-10   7.21  25.37  17.034286  1.71  ...  13.870000   6.75
1978-12-11/1978-12-17   8.04  18.05  14.987143  2.21  ...   9.168571   2.67
1978-12-18/1978-12-24   8.50  22.21  13.172857  1.00  ...   7.151429   4.71
1978-12-25/1978-12-31   7.83  27.29  16.035714  2.37  ...  10.868571   3.08

                                           BEL                      MAL  \
                         max       mean    min    max       mean    min
Date
1960-12-26/1961-01-01  12.58  12.580000  18.50  18.50  18.500000  15.04
1961-01-02/1961-01-08  10.46   8.497143   5.46  17.54  12.481429  10.88
1961-01-09/1961-01-15  14.58   7.571429   5.25  20.71  11.125714   5.17
1961-01-16/1961-01-22  16.71   8.124286   6.50  15.92   9.821429   6.79
1961-01-23/1961-01-29  19.95  15.640000  14.04  27.71  20.930000  17.50
...                      ...        ...    ...    ...        ...    ...
1978-11-27/1978-12-03  17.83   9.547143   4.92  21.42  11.835714  11.50
1978-12-04/1978-12-10  21.50  14.082857   9.54  26.08  18.517143  15.34
1978-12-11/1978-12-17  16.29   8.565714   5.00  21.50  11.102857   6.92
1978-12-18/1978-12-24  12.00   8.072857   3.21  19.79  11.845714  10.29
1978-12-25/1978-12-31  18.05  11.471429   1.21  21.79  12.947143  11.96


                         max       mean
Date
1960-12-26/1961-01-01  15.04  15.040000
1961-01-02/1961-01-08  16.46  13.238571
1961-01-09/1961-01-15  16.92  11.024286
1961-01-16/1961-01-22  17.96  11.434286
1961-01-23/1961-01-29  27.63  22.530000
...                      ...        ...
1978-11-27/1978-12-03  25.75  18.728571
1978-12-04/1978-12-10  34.59  23.061429
1978-12-11/1978-12-17  22.83  15.562857
1978-12-18/1978-12-24  31.71  18.977143
1978-12-25/1978-12-31  41.46  26.844286

[940 rows x 36 columns]