# Fictional Army - Filtering and Sorting

### Introduction:

This exercise was inspired by this [page](http://chrisalbon.com/python/)

Special thanks to: https://github.com/chrisalbon for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. This is the data given as a dictionary

In [2]:
# Create an example dataframe about a fictional army
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

### Step 3. Create a dataframe and assign it to a variable called army.

#### Don't forget to include the columns names in the order presented in the dictionary ('regiment', 'company', 'deaths'...) so that the column index order is consistent with the solutions. If omitted, pandas will order the columns alphabetically.

In [17]:
army = pd.DataFrame(raw_data)

### Step 4. Set the 'origin' colum as the index of the dataframe

In [27]:
army = army.reset_index()
army
army = army.set_index('origin')
army.loc['Arizona']

index                 0
regiment     Nighthawks
company             1st
deaths              523
battles               5
size               1045
veterans              1
readiness             1
armored               1
deserters             4
Name: Arizona, dtype: object

### Step 5. Print only the column veterans

In [28]:
army ['veterans']

origin
Arizona         1
California      5
Texas          62
Florida        26
Maine          73
Iowa           37
Alaska        949
Washington     48
Oregon         48
Wyoming       435
Louisana       63
Georgia       345
Name: veterans, dtype: int64

### Step 6. Print the columns 'veterans' and 'deaths'

In [31]:
army [['veterans', 'deaths']]

            veterans  deaths
origin
Arizona            1     523
California         5      52
Texas             62      25
Florida           26     616
Maine             73      43
Iowa              37     234
Alaska           949     523
Washington        48      62
Oregon            48      62
Wyoming          435      73
Louisana          63      37
Georgia          345      35

### Step 7. Print the name of all the columns.

In [32]:
army.columns

Index(['index', 'regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness', 'armored', 'deserters'],
      dtype='object')

### Step 8. Select the 'deaths', 'size' and 'deserters' columns from Maine and Alaska

In [36]:
army[['deaths', 'size', 'deserters']].loc[['Maine', 'Alaska']]

        deaths  size  deserters
origin
Maine       43  1592          3
Alaska     523   987         24

### Step 9. Select the rows 3 to 7 and the columns 3 to 6

In [38]:
army.iloc[2:7, 2:6]

        company  deaths  battles  size
origin
Texas       2nd      25        2  1099
Florida     2nd     616        2  1400
Maine       1st      43        4  1592
Iowa        1st     234        7  1006
Alaska      2nd     523        8   987

### Step 10. Select every row after the fourth row and all columns

In [39]:
army.iloc[4:, :]

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,,
Maine,4,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,5,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,6,Dragoons,2nd,523,8,987,949,2,0,24
Washington,7,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,8,Scouts,1st,62,4,973,48,2,0,2
Wyoming,9,Scouts,1st,73,7,1005,435,1,0,3
Louisana,10,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,11,Scouts,2nd,35,9,1523,345,3,1,3

### Step 11. Select every row up to the 4th row and all columns

In [40]:
army.iloc[:4, :]

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,,
Arizona,0,Nighthawks,1st,523,5,1045,1,1,1,4
California,1,Nighthawks,1st,52,42,957,5,2,0,24
Texas,2,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,3,Nighthawks,2nd,616,2,1400,26,3,1,2

### Step 12. Select the 3rd column up to the 7th column

In [68]:
army.iloc[:, 2:7]

           company  deaths  battles  size  veterans
origin
Arizona        1st     523        5  1045         1
California     1st      52       42   957         5
Texas          2nd      25        2  1099        62
Florida        2nd     616        2  1400        26
Maine          1st      43        4  1592        73
Iowa           1st     234        7  1006        37
Alaska         2nd     523        8   987       949
Washington     2nd      62        3   849        48
Oregon         1st      62        4   973        48
Wyoming        1st      73        7  1005       435
Louisana       2nd      37        8  1099        63
Georgia        2nd      35        9  1523       345

### Step 13. Select rows where df.deaths is greater than 50

In [43]:
army[army['deaths']>50]

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,,
Arizona,0,Nighthawks,1st,523,5,1045,1,1,1,4
California,1,Nighthawks,1st,52,42,957,5,2,0,24
Florida,3,Nighthawks,2nd,616,2,1400,26,3,1,2
Iowa,5,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,6,Dragoons,2nd,523,8,987,949,2,0,24
Washington,7,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,8,Scouts,1st,62,4,973,48,2,0,2
Wyoming,9,Scouts,1st,73,7,1005,435,1,0,3

### Step 14. Select rows where df.deaths is greater than 500 or less than 50

In [46]:
army [(army['deaths']<50) | (army['deaths'] > 500)]

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,,
Arizona,0,Nighthawks,1st,523,5,1045,1,1,1,4
Texas,2,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,3,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,4,Dragoons,1st,43,4,1592,73,2,0,3
Alaska,6,Dragoons,2nd,523,8,987,949,2,0,24
Louisana,10,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,11,Scouts,2nd,35,9,1523,345,3,1,3

### Step 15. Select all the regiments not named "Dragoons"

In [47]:
army [army['regiment'] != 'Dragoons']

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,,
Arizona,0,Nighthawks,1st,523,5,1045,1,1,1,4
California,1,Nighthawks,1st,52,42,957,5,2,0,24
Texas,2,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,3,Nighthawks,2nd,616,2,1400,26,3,1,2
Oregon,8,Scouts,1st,62,4,973,48,2,0,2
Wyoming,9,Scouts,1st,73,7,1005,435,1,0,3
Louisana,10,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,11,Scouts,2nd,35,9,1523,345,3,1,3

### Step 16. Select the rows called Texas and Arizona

In [49]:
army.loc[['Texas', 'Arizona']]

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,,
Texas,2,Nighthawks,2nd,25,2,1099,62,3,1,31
Arizona,0,Nighthawks,1st,523,5,1045,1,1,1,4

### Step 17. Select the third cell in the row named Arizona

In [64]:
army.loc['Arizona'].iloc[2]

#

'1st'

### Step 18. Select the third cell down in the column named deaths

In [67]:
army['deaths'].iloc[2]

np.int64(25)